/**
 * generate-sw.mjs
 * ─────────────────────────────────────────────────────────────
 * Run AFTER `next build` to produce public/sw.js with a
 * precache manifest of every hashed _next/static/ asset.
 *
 * Usage (package.json):
 *   "build": "next build && node scripts/generate-sw.mjs"
 */

import { readFileSync, writeFileSync, readdirSync, statSync } from 'fs';
import { join, relative } from 'path';
import { fileURLToPath } from 'url';

const __dirname = fileURLToPath(new URL('.', import.meta.url));
const ROOT = join(__dirname, '..');
const NEXT_STATIC = join(ROOT, '.next', 'static');
const PUBLIC_SW = join(ROOT, 'public', 'sw.js');

// ── 1. Collect all files under .next/static/ ─────────────────────────────────
function walk(dir, base = dir) {
  const entries = readdirSync(dir, { withFileTypes: true });
  const results = [];
  for (const entry of entries) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      results.push(...walk(full, base));
    } else {
      // Convert Windows backslashes → forward slashes for URL paths
      const rel = relative(base, full).replace(/\\/g, '/');
      results.push(rel);
    }
  }
  return results;
}

let staticFiles = [];
try {
  staticFiles = walk(NEXT_STATIC);
} catch {
  console.warn('[generate-sw] .next/static not found — skipping static precache.');
}

// Build URL list: /_next/static/<rel>
const staticUrls = staticFiles
  .filter(f => f.endsWith('.js') || f.endsWith('.css') || f.endsWith('.json') || f.endsWith('.woff2') || f.endsWith('.woff'))
  .map(f => `/_next/static/${f}`);

// ── 2. Read build-manifest for root main files (polyfills etc.) ───────────────
let rootMainFiles = [];
try {
  const manifest = JSON.parse(readFileSync(join(ROOT, '.next', 'build-manifest.json'), 'utf8'));
  rootMainFiles = (manifest.rootMainFiles || []).map(f => `/_next/${f}`);
} catch {
  console.warn('[generate-sw] build-manifest.json not found — skipping rootMainFiles.');
}

// ── 3. Static public assets to always precache ───────────────────────────────
const PUBLIC_ASSETS = [
  '/manifest.json',
  '/sounds/soft-chime.mp3',
  '/sounds/completion-tone.mp3',
  '/sounds/notification-tone.mp3',
  '/sounds/success-bell.mp3',
  '/images/logo.svg',
  '/images/mic.svg',
  '/images/mic2.svg',
  '/images/micgray.svg',
  '/images/privacy.svg',
  '/images/replay.svg',
  '/images/selected.svg',
  '/images/alert-circle.svg',
  '/images/audio-wave.svg',
  '/images/change.svg',
  '/images/pause.svg',
  '/images/play.svg',
  '/images/tooltip.svg',
  '/images/islamicpattern.png',
  '/icons/icon-192x192.png',
  '/icons/icon-512x512.png',
];

// App shell HTML pages — these will be network-fetched during install
const APP_SHELL_PAGES = ['/', '/ar', '/en', '/ar/home', '/en/home', '/ar/session', '/en/session'];

const ALL_PRECACHE = [...new Set([...PUBLIC_ASSETS, ...staticUrls, ...rootMainFiles])];

console.log(`[generate-sw] Precaching ${ALL_PRECACHE.length} assets (${staticUrls.length} _next/static chunks)`);

// ── 4. Generate sw.js ─────────────────────────────────────────────────────────
const swContent = `// AUTO-GENERATED by scripts/generate-sw.mjs — do not edit manually.
// Regenerated on every \`npm run build\`.

const CACHE_NAME = 'zekr-v5';

// All hashed _next/static/ chunks + public assets baked in at build time.
// These are safe to cache permanently (content-hashed filenames).
const PRECACHE_URLS = ${JSON.stringify(ALL_PRECACHE, null, 2)};

// App shell pages (HTML). Fetched during install so the app works offline
// from the very first open after a fresh install.
const APP_SHELL_PAGES = ${JSON.stringify(APP_SHELL_PAGES, null, 2)};

// ─── Install: precache everything we know about ───────────────────────────────
self.addEventListener('install', (event) => {
  self.skipWaiting();
  event.waitUntil(
    caches.open(CACHE_NAME).then(async (cache) => {
      // 1. Cache all static assets (best-effort — individual failures ignored)
      await Promise.allSettled(
        PRECACHE_URLS.map((url) =>
          cache.add(url).catch(() => {})
        )
      );

      // 2. Fetch & cache app shell HTML pages so navigation works offline.
      //    The SW fetch handler below intercepts every _next/ sub-request
      //    that the page loads, caching them too.
      await Promise.allSettled(
        APP_SHELL_PAGES.map((page) =>
          fetch(page, { credentials: 'same-origin' })
            .then((res) => {
              if (res && res.status === 200) {
                return cache.put(page, res);
              }
            })
            .catch(() => {})
        )
      );
    })
  );
});

// ─── Activate: remove old caches ─────────────────────────────────────────────
self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) =>
        Promise.all(
          keys.filter((k) => k !== CACHE_NAME).map((k) => caches.delete(k))
        )
      )
      .then(() => self.clients.claim())
  );
});

// ─── Fetch ────────────────────────────────────────────────────────────────────
self.addEventListener('fetch', (event) => {
  const { request } = event;
  const url = new URL(request.url);

  // Only handle same-origin GET requests over http(s)
  if (
    request.method !== 'GET' ||
    !url.protocol.startsWith('http') ||
    url.origin !== self.location.origin
  ) {
    return;
  }

  // ── Cache-First: immutable _next/static/ chunks
  if (url.pathname.startsWith('/_next/static/')) {
    event.respondWith(
      caches.match(request).then((cached) => {
        if (cached) return cached;
        return fetch(request).then((res) => {
          if (res && res.status === 200) {
            const clone = res.clone();
            caches.open(CACHE_NAME).then((c) => c.put(request, clone));
          }
          return res;
        }).catch(() => new Response('', { status: 503 }));
      })
    );
    return;
  }

  // ── Cache-First: static media (images, sounds, icons)
  if (
    url.pathname.startsWith('/images/') ||
    url.pathname.startsWith('/sounds/') ||
    url.pathname.startsWith('/icons/') ||
    url.pathname.endsWith('.png') ||
    url.pathname.endsWith('.svg') ||
    url.pathname.endsWith('.mp3') ||
    url.pathname.endsWith('.webp') ||
    url.pathname.endsWith('.woff2') ||
    url.pathname.endsWith('.woff')
  ) {
    event.respondWith(
      caches.match(request).then((cached) => {
        if (cached) {
          fetch(request).then((res) => {
            if (res && res.status === 200) {
              caches.open(CACHE_NAME).then((c) => c.put(request, res));
            }
          }).catch(() => {});
          return cached;
        }
        return fetch(request).then((res) => {
          if (res && res.status === 200) {
            const clone = res.clone();
            caches.open(CACHE_NAME).then((c) => c.put(request, clone));
          }
          return res;
        }).catch(() => new Response('', { status: 503 }));
      })
    );
    return;
  }

  // ── Stale-While-Revalidate: _next/data/ routes
  if (url.pathname.startsWith('/_next/data/')) {
    event.respondWith(
      caches.open(CACHE_NAME).then(async (cache) => {
        const cached = await cache.match(request);
        const fetchPromise = fetch(request)
          .then((res) => {
            if (res && res.status === 200) cache.put(request, res.clone());
            return res;
          })
          .catch(() => cached || new Response('{}', { status: 503 }));
        return cached || fetchPromise;
      })
    );
    return;
  }

  // ── Network-First with Cache fallback: HTML pages / app routes
  event.respondWith(
    fetch(request)
      .then((res) => {
        if (res && res.status === 200) {
          const clone = res.clone();
          caches.open(CACHE_NAME).then((c) => c.put(request, clone));
        }
        return res;
      })
      .catch(async () => {
        const cached = await caches.match(request);
        if (cached) return cached;

        // For HTML navigations, serve the locale home page as app shell
        if (request.headers.get('accept')?.includes('text/html')) {
          const locale = url.pathname.startsWith('/ar') ? 'ar' : 'en';
          const shell =
            await caches.match('/' + locale + '/home') ||
            await caches.match('/' + locale) ||
            await caches.match('/ar/home') ||
            await caches.match('/');
          if (shell) return shell;
        }

        return new Response('Offline', { status: 503, statusText: 'Offline' });
      })
  );
});
`;

writeFileSync(PUBLIC_SW, swContent, 'utf8');
console.log(`[generate-sw] ✅ Written: public/sw.js`);
